version: '3.8'
services:
  db:
    image: ankane/pgvector:latest
    container_name: server_postgres_vector
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '1111'
      POSTGRES_DB: finance_db
    volumes:
      - ./server_postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    restart: always
